# Generated by Django 2.1.3 on 2018-11-13 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Чек',
                'verbose_name': 'Checks',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Отдел',
                'verbose_name': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Meal_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Department')),
            ],
            options={
                'verbose_name_plural': 'Блюдо по отделам',
                'verbose_name': 'Meal Categories',
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Meal_Categories')),
            ],
            options={
                'verbose_name_plural': 'Блюдо',
                'verbose_name': 'Meal',
            },
        ),
        migrations.CreateModel(
            name='MealsToOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Meals')),
            ],
            options={
                'verbose_name_plural': 'Распределение по заказам',
                'verbose_name': 'ToOrder',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(max_length=20)),
                ('mealsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Meals')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Должность',
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=15)),
            ],
            options={
                'verbose_name_plural': 'Проценты',
                'verbose_name': 'Percent',
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='in progress', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Статус',
                'verbose_name': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Стол',
                'verbose_name': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Roles')),
            ],
            options={
                'verbose_name_plural': 'Персонал',
                'verbose_name': 'Users',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Statuses'),
        ),
        migrations.AddField(
            model_name='order',
            name='tableid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Tables'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Users'),
        ),
        migrations.AddField(
            model_name='mealstoorder',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='check',
            name='meals',
            field=models.ManyToManyField(to='order.Meals'),
        ),
        migrations.AddField(
            model_name='check',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='check',
            name='percentage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ServicePercentage'),
        ),
    ]
