# Generated by Django 2.1.3 on 2018-11-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealstoorder',
            old_name='count',
            new_name='quantity',
        ),
    ]
