# Generated by Django 2.1.3 on 2018-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_users_roleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('waiter', 'WAITER'), ('chief', 'CHIEF')], default=None, max_length=50),
        ),
    ]
