# Generated by Django 2.1.3 on 2018-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(choices=[('waiter', 'WAITER'), ('chief', 'CHIEF')], max_length=50),
        ),
    ]
