# Generated by Django 2.1.3 on 2018-11-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20181122_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateborn', models.DateField()),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Roles')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(choices=[('waiter', 'WAITER'), ('chief', 'CHIEF')], default='waiter', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
