# Generated by Django 2.1.3 on 2018-11-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181123_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('waiter', 'WAITER'), ('chief', 'CHIEF'), ('admin', 'ADMIN'), ('stripgirl', 'STRIPTISE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(choices=[('waiter', 'WAITER'), ('chief', 'CHIEF'), ('admin', 'ADMIN'), ('stripgirl', 'STRIPTISE')], default='waiter', max_length=50),
        ),
    ]
