# Generated by Django 2.1.3 on 2018-11-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20181127_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealstoorder',
            name='quantity',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
