# Generated by Django 2.1.3 on 2018-11-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20181127_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
