# Generated by Django 2.1.3 on 2018-11-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20181127_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profiles', 'verbose_name_plural': 'Профили'},
        ),
    ]
